#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  HTServo)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     kGyroSensor,    sensorI2CHiTechnicGyro)
#pragma config(Sensor, S3,     HTIRS2,              sensorI2CCustom)
#pragma config(Sensor, S4,     touch,          sensorTouch)
#pragma config(Motor,  mtr_S1_C1_1,     LeftSideMotors, tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     RightSideMotors, tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     conveyor1,     tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     stacker,       tmotorNormal, openLoop, reversed, encoder)
#pragma config(Servo,  srvo_S1_C3_1,    servoCrateL,          tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    servoCrateR,          tServoStandard)
#pragma config(Servo,  srvo_S1_C3_3,    servoGripL,           tServoStandard)
#pragma config(Servo,  srvo_S1_C3_4,    servoGripR,           tServoStandard)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "constants.c"
#include "driveMover.c"
#include "JoystickDriver.c" // there's a joystick attached
#include "MovesAuto.c"


////////////////////////////////////////
void initializeRobot(){
  //servoChangeRate[SERVOGATE]   = 10;
  servoChangeRate[ServoCrateL]   = 20;
  servoChangeRate[ServoCrateR]   = 20;
  //servoChangeRate[servoFlip] = 10;
  //servoChangeRate[hopControl] = 20;
  //servo[servoFlip] = SERVOARMUP;
  //servo[SERVOGATE]  =  SERVOGATEOPEN;
  servo[servoCrateL]  =  CRATELUP;
  servo[servoCrateR]  =  CRATERUP;
  servo[servoGripL]  =  GRIPLWIDE;
  servo[servoGripR]  =  GRIPRWIDE;
  //servo[hopControl] = HOPCONTROLCLOSED;
  nMotorEncoder[stacker]=0;
  gyroFlasher();
}

task main() {
  initializeRobot();
  wait1msec(1000); wait1msec(200);
  /*distForward(15); wait1msec(500);
  //while(true){anglereading();}
  turnRightTo(90); wait1Msec(500);
  //turnLeftTo(0); wait1Msec(500);
  distForward(10); wait1Msec(500);
  turnRightTo(180); wait1Msec(1000);
  distForward(15); wait1Msec(500);
  */turnLeftTo(-90); wait1Msec(500);
  //distForward(10); wait1Msec(500);
  turnRightTo(0);
}
