#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S1,     ,                    sensorI2CMuxController)
#pragma config(Sensor, S2,     sonarL,              sensorSONAR)
#pragma config(Sensor, S3,     sonarR,              sensorSONAR)
#pragma config(Sensor, S4,     touch,               sensorTouch)
#pragma config(Motor,  mtr_S1_C1_1,     LeftSideMotors, tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     RightSideMotors, tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     conveyor1,     tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     stacker,       tmotorNormal, openLoop, reversed, encoder)
#pragma config(Servo,  srvo_S1_C3_1,    servoGate,            tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    servoCrateL,          tServoStandard)
#pragma config(Servo,  srvo_S1_C3_3,    servoCrateR,          tServoStandard)
#pragma config(Servo,  srvo_S1_C3_4,    servoGripL,           tServoStandard)
#pragma config(Servo,  srvo_S1_C3_5,    servoGripR,           tServoStandard)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "constants.c"
#include "driveMover.c"
#include "JoystickDriver.c" // there's a joystick attached
#include "MovesAuto.c"

////////////////////////////////////////
void initializeRobot(){
  servoChangeRate[SERVOGATE]   = 10;
  servoChangeRate[ServoCrateL]   = 20;
  servoChangeRate[ServoCrateR]   = 20;
  //servoChangeRate[servoFlip] = 10;
  //servoChangeRate[hopControl] = 20;
  //servo[servoFlip] = SERVOARMUP;
  servo[SERVOGATE]  =  SERVOGATEOPEN;
  servo[servoCrateL]  =  CRATELUP;
  servo[servoCrateR]  =  CRATERUP;
  servo[servoGripL]  =  GRIPLWIDE;
  servo[servoGripR]  =  GRIPRWIDE;
  //servo[hopControl] = HOPCONTROLCLOSED;
  nMotorEncoder[stacker]=0;
}

task main(){
  initializeRobot();
  wait1Msec(3000);
  while(nMotorEncoder[stacker]<armlimitup+200){
    motor[stacker]=100;
  }
    motor[stacker]=0;

}




