#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Motor,  mtr_S1_C1_1,     motorChain,    tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorNone, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

task main()
{
  while(true)
  {
  getJoystickSettings(joystick);
  motor[motorChain]=((-100*joystick.joy1_y1)/500);
  }
  //motor[motorChain]=10;
  //wait1Msec(500);
}
