#define SERVOGATEOPEN 160
#define SERVOGATECLOSE 0
#define SERVOARMUP 0
#define SERVOARMDOWN 175
#define HOPCONTROLUP 0
#define HOPCONTROLDOWN 180
#define HOPCONTROLCLOSED 80
#define HOPCONTROLP1 80
#define HOPCONTROLP2 45

////////////
