#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  HTMotor)
#pragma config(Sensor, S2,     kGyroSensor,    sensorI2CHiTechnicGyro)
#pragma config(Sensor, S3,     RSonar,         sensorSONAR)
#pragma config(Sensor, S4,     LSonar,         sensorSONAR)
#pragma config(Motor,  motorB,          catchR,        tmotorNormal, PIDControl, encoder)
#pragma config(Motor,  motorC,          catchL,        tmotorNormal, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     LeftSideMotors, tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     RightSideMotors, tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     conveyor1,     tmotorNormal, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     stacker,       tmotorNormal, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C4_1,     spoolL,        tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     spoolR,        tmotorNormal, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    servoCrateL,          tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    servoCrateR,          tServoStandard)
#pragma config(Servo,  srvo_S1_C3_3,    servoGripL,           tServoStandard)
#pragma config(Servo,  srvo_S1_C3_4,    servoGripR,           tServoStandard)
#pragma config(Servo,  srvo_S1_C3_5,    hookL,                tServoStandard)
#pragma config(Servo,  srvo_S1_C3_6,    hookR,                tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "constants.c"
#include "driveMover.c"
#include "JoystickDriver.c" // there's a joystick attached
#include "MovesAuto.c"

////////////////////////////////////////
void initializeRobot(){
  //servoChangeRate[SERVOGATE]   = 10;
  servoChangeRate[ServoCrateL]   = 20;
  servoChangeRate[ServoCrateR]   = 20;
  servoChangeRate[hookL]   = 20;
  servoChangeRate[hookR]   = 20;
  //servoChangeRate[servoFlip] = 10;
  //servoChangeRate[hopControl] = 20;
  //servo[servoFlip] = SERVOARMUP;
  //servo[SERVOGATE]  =  SERVOGATEOPEN;
  servo[servoCrateL]  =  CRATELUP;
  servo[servoCrateR]  =  CRATERUP;
  servo[servoGripL]  =  GRIPLTHIN;
  servo[servoGripR]  =  GRIPRTHIN;
  servo[hookL]  =  hookfoldL;
  servo[hookR]  =  hookfoldR;
  //servo[hopControl] = HOPCONTROLCLOSED;
  nMotorEncoder[stacker]=0;
  motor[motorB]=-50;
  motor[motorC]=-50;
  wait1Msec(250);
  nMotorEncoder[motorB]=0;
  nMotorEncoder[motorC]=0;
  motor[motorB]=0;
  motor[motorC]=0;
}

task main()
{
 bool goesback=false;
 initializeRobot();
 waitForStart();
 distForward(42);wait1Msec(300);
 ClearTimer(T1);
 while(SensorValue[LSonar]>8 && time1(T1)<2000)
 {
   standardDrive(50,50);
 }
 standardDrive(0,0);wait1Msec(300);
 if(SensorValue[LSonar]>8)
 {
   goesback=true;ClearTimer(T1);
   while(SensorValue[LSonar]>8 && time1(T1)<1000)
   {
     standardDrive(-100,-100);
   }
 }
 standardDrive(0,0);wait1Msec(300)
 if(!goesback)
 {
   distForward(15);wait1Msec(200);
 }
 else
 {
   distForward(19);wait1Msec(200);
 }
 turnRSideTo(45);wait1Msec(300);
 slowBackward(60);wait1Msec(200);
 slowForward(8);wait1Msec(300);
 turnRSideTo(90);wait1Msec(300);
 slowBackward(24);wait1Msec(300);
 standardDrive(0,0);wait1Msec(300);
}
