#pragma config(Sensor, S1,     kGyroSensor,         sensorI2CHiTechnicGyro)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "CHSGyroDriver.c"

task main()
{
  bool bFlasher = false;
  float fOldAngle = -1;

  //
  // Initialize Display
  //
  eraseDisplay();
  nxtDisplayBigStringAt(25, 55, "Gyro");
  nxtDisplayBigStringAt(15, 39, "Angle");

  //
  // Wait for gyro to stablize. This takes a few seconds. If you don't want to wait you can modify the
  // driver and make the sensor bias value a constant rather than calculated. Just run the routine a few
  // times to see what the calculated value is and then use this as the constant!
  //
  while (!bIsGyroInitialized())
  {
    if (bIsGyroInitialized())
      break;

    //
    // Some flashy graphics.
    //
    if (bFlasher)
    {
      nxtDisplayBigStringAt(0, 23, " Startup ");
      bFlasher = false;
    }
    else
    {
      nxtDisplayBigStringAt(0, 23, "        ");
      bFLasher = true;
    }
    wait1Msec(250);// Wait for the gyro to initialize. This takes a couple of seconds.
  }

  //
  // Loop forever displaying the gyro angle on the screen
  //

  while (true)
  {
    if (fGyroAngle != fOldAngle)
    {
      nxtDisplayBigStringAt(0, 23, "  %3d   ", (long) fGyroAngle);
      fOldAngle = fGyroAngle;
    }
    wait1Msec(3);
  }
}
