#pragma config(Sensor, S1,     gyrosense,           sensorI2CHiTechnicGyro)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main() {
  int fGyroAngle;
  while(true){
    SensorValue[gyrosense] = fGyroAngle;
    nxtDisplayBigStringAt(0, 23, "  %3d   ", (long) fGyroAngle);
  }
}
