#pragma config(Sensor, S1,     gyro,                sensorI2CHiTechnicGyro)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "HTGYRO-driver.h"

/*
void integrate(){
  angv = HTGYROreadRot(gyro);
}
*/
task main(){
  HTGYROstartCal(gyro);
  int value;
  while(true){
    value = HTGYROreadRot(gyro);
    nxtDisplayTextLine(4, "AngV:   %4d", value);
  }
}
