#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  HTMotor)
#pragma config(Sensor, S2,     kGyroSensor,    sensorI2CHiTechnicGyro)
#pragma config(Motor,  motorB,          catchR,        tmotorNormal, PIDControl, encoder)
#pragma config(Motor,  motorC,          catchL,        tmotorNormal, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     LeftSideMotors, tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     RightSideMotors, tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     conveyor1,     tmotorNormal, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     stacker,       tmotorNormal, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C4_1,     spoolL,        tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     spoolR,        tmotorNormal, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    servoCrateL,          tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    servoCrateR,          tServoStandard)
#pragma config(Servo,  srvo_S1_C3_3,    servoGripL,           tServoStandard)
#pragma config(Servo,  srvo_S1_C3_4,    servoGripR,           tServoStandard)
#pragma config(Servo,  srvo_S1_C3_5,    hookL,                tServoStandard)
#pragma config(Servo,  srvo_S1_C3_6,    hookR,                tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "constants.c"
#include "driveMover.c"
#include "JoystickDriver.c" // there's a joystick attached
#include "MovesAuto.c"

////////////////////////////////////////
void initializeRobot(){
  //servoChangeRate[SERVOGATE]   = 10;
  servoChangeRate[ServoCrateL]   = 20;
  servoChangeRate[ServoCrateR]   = 20;
  servoChangeRate[hookL]   = 20;
  servoChangeRate[hookR]   = 20;
  //servoChangeRate[servoFlip] = 10;
  //servoChangeRate[hopControl] = 20;
  //servo[servoFlip] = SERVOARMUP;
  //servo[SERVOGATE]  =  SERVOGATEOPEN;
  servo[servoCrateL]  =  CRATELUP;
  servo[servoCrateR]  =  CRATERUP;
  servo[servoGripL]  =  GRIPLTHIN;
  servo[servoGripR]  =  GRIPRTHIN;
  servo[hookL]  =  hookfoldL;
  servo[hookR]  =  hookfoldR;
  //servo[hopControl] = HOPCONTROLCLOSED;
  nMotorEncoder[stacker]=0;
  motor[motorB]=-50;
  motor[motorC]=-50;
  wait1Msec(250);
  nMotorEncoder[motorB]=0;
  nMotorEncoder[motorC]=0;
  motor[motorB]=0;
  motor[motorC]=0;
}

typedef enum {blue,red} Tstartside;
typedef enum {getball,crates,defense} Tstrategy;

task main()
{
  bool gonext; //used to gate input/output
  int initialDelay=0;
  Tstartside startside=blue;
  Tstrategy  strategy=getball;

  //BEGINNING OF NXT BUTTON INPUT
  gonext=false;
  nNxtButtonTask=0;
  hogCPU();

  //SIDE SELECTION
  while(!gonext){

      nxtDisplayCenteredBigTextLine(1, "SIDE");
      if(startside==blue) nxtDisplayCenteredBigTextLine(3, "BLUE");
      if(startside==red)  nxtDisplayCenteredBigTextLine(3, "RED");


    if(nNxtButtonPressed == 1) startside=blue;
    if(nNxtButtonPressed == 2) startside=red;
    if(nNxtButtonPressed == 3) gonext=true;
    if(nNxtButtonPressed>=0)ClearTimer(T1); while(time1[T1]<300);
  }
  ClearTimer(T1); while(time1[T1]<500);

  //QUERY strategy
  gonext=false;

  while(!gonext){
    if(startside==blue) nxtDisplayCenteredBigTextLine(1, "BLUE");
    if(startside==red) nxtDisplayCenteredBigTextLine(1, "RED");

    if(strategy==getball) nxtDisplayCenteredBigTextLine(3, "GETBALL");
    if(strategy==crates) nxtDisplayCenteredBigTextLine(3, "CRATES");
    if(strategy==defense) nxtDisplayCenteredBigTextLine(3, "DEFENSE");


    if(nNxtButtonPressed == 1) { strategy=(strategy+1)%3; }
    if(nNxtButtonPressed == 2) { strategy=(strategy+4)%3; }
    if(nNxtButtonPressed == 3) gonext=true;
    if(nNxtButtonPressed>=0)ClearTimer(T1); while(time1[T1]<300);
  }

  ClearTimer(T1); while(time1[T1]<500);
  gonext=false;

  while(!gonext){
    if(startside==blue) nxtDisplayCenteredBigTextLine(1, "BLUE");
    if(startside==red) nxtDisplayCenteredBigTextLine(1, "RED");

    if(strategy==getball) nxtDisplayCenteredBigTextLine(3, "GETBALL");
    if(strategy==crates) nxtDisplayCenteredBigTextLine(3, "CRATES");
    if(strategy==defense) nxtDisplayCenteredBigTextLine(3, "DEFENSE");

    nxtDisplayCenteredBigTextLine(5, "DE %d",initialDelay);

    if(nNxtButtonPressed == 1) { initialDelay=initialDelay+500; }
    if(nNxtButtonPressed == 2) {
      if(initialDelay>0) initialDelay=initialDelay-500;
    }
    if(nNxtButtonPressed == 3) gonext=true;
    if(nNxtButtonPressed>=0)ClearTimer(T1); while(time1[T1]<300);
  }

  if(startside==blue) nxtDisplayCenteredBigTextLine(1, "SET BLUE");
  if(startside==red) nxtDisplayCenteredBigTextLine(1, "SET RED");

  if(strategy==getball) nxtDisplayCenteredBigTextLine(3, "GETBALL");
  if(strategy==crates) nxtDisplayCenteredBigTextLine(3, "CRATES");
  if(strategy==defense) nxtDisplayCenteredBigTextLine(3, "DEFENSE");

  nxtDisplayCenteredBigTextLine(5, "DE %d",initialDelay);

  ClearTimer(T1); while(time1[T1]<5000);

  nNxtButtonTask=-1;
  releaseCPU();

  InitializeRobot();

	waitForStart();

	wait1Msec(initialDelay);

  ClearTimer(T1);  //we can use timer T1 to wait etc
                   //we should use time100 timer since that allows enough time for autonomous
                   //time100[T1]=300 is end of autonomous

  //advance to goal and turn
  if(startside==blue){
    switch(strategy){
      case getball:
      distForward(42, medium);wait1Msec(200);
      turnRightTo(45,50);wait1Msec(200);
      distForward(16, slow);wait1Msec(200);
      distBackward(6, medium);wait1Msec(200);
      turnLeftTo(-45,50);wait1Msec(200);
      distBackward(102, fast);
      break;
      case crates:
      distForward(33, slow);wait1Msec(200);
      turnRightTo(45, 50);wait1Msec(200);
      distForward(20, slow);wait1Msec(200);
      distBackward(10, medium);wait1Msec(200);
      turnLeftTo(10, 40);wait1Msec(200);
      distForward(39, medium);wait1Msec(200);
      turnRightTo(135, 100);wait1Msec(200);
      break;
      case defense:
      distForward(42, medium);wait1Msec(200);
      turnRightTo(45, 100);wait1Msec(200);
      distForward(85, fast);
      break;
    }
  }

  if(startside==red){ //RED SIDE
    switch(strategy){
      case getball:
      distForward(42, medium);wait1Msec(200);
      turnLeftTo(-45,50);wait1Msec(200);
      distForward(16, slow);wait1Msec(200);
      distBackward(6, medium);wait1Msec(200);
      turnRightTo(45,50);wait1Msec(200);
      distBackward(102, fast);
      break;
      case crates:
      distForward(33, slow);wait1Msec(200);
      turnLeftTo(-45, 50);wait1Msec(200);
      distForward(20, slow);wait1Msec(200);
      distBackward(10, medium);wait1Msec(200);
      turnRightTo(-10, 40);wait1Msec(200);
      distForward(39, medium);wait1Msec(200);
      turnLeftTo(-135, 100);wait1Msec(200);
      break;
      case defense:
      distForward(42, medium);wait1Msec(200);
      turnLeftTo(-45, 100);wait1Msec(200);
      distForward(85, fast);
      break;
    }
  }

}
