#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  HTMotor)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  motorA,          flipper,       tmotorNormal, openLoop, encoder)
#pragma config(Motor,  motorB,          catchR,        tmotorNormal, openLoop, encoder)
#pragma config(Motor,  motorC,          catchL,        tmotorNormal, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     LeftSideMotors, tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     RightSideMotors, tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     conveyor1,     tmotorNormal, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     stacker,       tmotorNormal, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C4_1,     spoolL,        tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     spoolR,        tmotorNormal, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    servoCrateL,          tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    servoCrateR,          tServoStandard)
#pragma config(Servo,  srvo_S1_C3_3,    servoGripL,           tServoStandard)
#pragma config(Servo,  srvo_S1_C3_4,    servoGripR,           tServoStandard)
#pragma config(Servo,  srvo_S1_C3_5,    hookL,                tServoStandard)
#pragma config(Servo,  srvo_S1_C3_6,    hookR,                tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//*****************************************************************
//
//
// started 10/24/10
//*****************************************************************

#include "constants.c"


task main() {

  //NXT conveyor control
  int conveyorDirection=0;

  nNxtButtonTask=0;
  hogCPU();

  while(true){

    nxtDisplayCenteredBigTextLine(1, "CONVEY");

    wait1Msec(100);

    conveyorDirection=0;

    if(nNxtButtonPressed == 0) {return;}
    if(nNxtButtonPressed == 1) {conveyorDirection=1;}
    if(nNxtButtonPressed == 2) {conveyorDirection=-1;}

    switch(conveyorDirection){
      case -1:
       motor[conveyor1]=-100;
      break;
      case 1:
       motor[conveyor1]=100;
      break;
      default:
      motor[conveyor1]=0;
    }
  }
}
