#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Motor,  mtr_S1_C1_1,     motorFL,       tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorBR,       tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     motorFR,       tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorBL,       tmotorNormal, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

int motorPower;
int FlBrPower;
int FRBlPower;

task main()
{
  while(true)
  {

motorPower=(int)floor(sqrt((float)(joystick.joy1_y1*joystick.joy1_y1+joystick.joy1_x1*joystick.joy1_x1))/127);




motorFL= -(FlBrPower);
motorBR= (FlBrPower);

motorFR= (FrBlPower);
motorBL= -(FrBlPower);

  }
}
