#pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)
#pragma config(Sensor, S2,     sonarL,              sensorSONAR)
#pragma config(Sensor, S3,     sonarR,              sensorSONAR)
#pragma config(Sensor, S4,     touch,         sensorTouch)
#pragma config(Motor,  mtr_S1_C1_1,     LeftSideMotors, tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     RightSideMotors, tmotorNormal, openLoop)
#pragma config(Servo,  srvo_S1_C2_1,    servoGate,            tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


//*****************************************************************
//
//
//*****************************************************************

#include "constants.c"
#include "driveMover.c"

#include "JoystickDriver.c" // there's a joystick attached

#include "MovesAuto.c"

task main()
{
  int i;
  wait1Msec(1000);
//rotation testing
  /*
  for(i=0;i<4;i++){
    turnRight90();
    wait1Msec(300);
  }
  wait1Msec(1000);
*/
//distance testing
  //driveNudge(100,100,1000);
  distForward(20.0);

}
