#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  HTMotor)
#pragma config(Sensor, S2,     kGyroSensor,    sensorI2CHiTechnicGyro)
#pragma config(Sensor, S3,     RSonar,         sensorSONAR)
#pragma config(Sensor, S4,     LSonar,         sensorSONAR)
#pragma config(Motor,  motorB,          catchR,        tmotorNormal, PIDControl, encoder)
#pragma config(Motor,  motorC,          catchL,        tmotorNormal, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     LeftSideMotors, tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     RightSideMotors, tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     conveyor1,     tmotorNormal, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     stacker,       tmotorNormal, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C4_1,     spoolL,        tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     spoolR,        tmotorNormal, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    servoCrateL,          tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    servoCrateR,          tServoStandard)
#pragma config(Servo,  srvo_S1_C3_3,    servoGripL,           tServoStandard)
#pragma config(Servo,  srvo_S1_C3_4,    servoGripR,           tServoStandard)
#pragma config(Servo,  srvo_S1_C3_5,    hookL,                tServoStandard)
#pragma config(Servo,  srvo_S1_C3_6,    hookR,                tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "constants.c"
#include "driveMover.c"
#include "JoystickDriver.c" // there's a joystick attached
#include "MovesAuto.c"

////////////////////////////////////////
void initializeRobot(){
  //servoChangeRate[SERVOGATE]   = 10;
  servoChangeRate[ServoCrateL]   = 20;
  servoChangeRate[ServoCrateR]   = 20;
  servoChangeRate[hookL]   = 20;
  servoChangeRate[hookR]   = 20;
  //servoChangeRate[servoFlip] = 10;
  //servoChangeRate[hopControl] = 20;
  //servo[servoFlip] = SERVOARMUP;
  //servo[SERVOGATE]  =  SERVOGATEOPEN;
  servo[servoCrateL]  =  CRATELUP;
  servo[servoCrateR]  =  CRATERUP;
  servo[servoGripL]  =  GRIPLTHIN;
  servo[servoGripR]  =  GRIPRTHIN;
  servo[hookL]  =  hookfoldL;
  servo[hookR]  =  hookfoldR;
  //servo[hopControl] = HOPCONTROLCLOSED;
  nMotorEncoder[stacker]=0;
  motor[motorB]=-50;
  motor[motorC]=-50;
  wait1Msec(250);
  nMotorEncoder[motorB]=0;
  nMotorEncoder[motorC]=0;
  motor[motorB]=0;
  motor[motorC]=0;
}


task main()
{
    bool gonext; //used to gate input/output
  bool blueSide=false;
  bool getBowlBall=false;

  //BEGINNING OF NXT BUTTON INPUT
  gonext=false;
  nNxtButtonTask=0;
  hogCPU();

  //SIDE SELECTION
  while(!gonext){

    ClearTimer(T1);
      nxtDisplayCenteredBigTextLine(1, "SIDE");
      if(blueSide) nxtDisplayCenteredBigTextLine(3, "BLUE");
      else          nxtDisplayCenteredBigTextLine(3, "RED");

    while(time10[T1]<20);
    if(nNxtButtonPressed == 1) blueSide=true;
    if(nNxtButtonPressed == 2) blueSide=false;
    if(nNxtButtonPressed == 3) gonext=true;
  }

  if(blueSide) {
    ClearTimer(T1);
    while(time10[T1]<50);  //wait for 1/2 second to make sure button released
  }
  else {
    ClearTimer(T1);
    while(time10[T1]<50);  //wait for 1/2 second to make sure button released
  }

  nNxtButtonTask=-1;
  releaseCPU();

  InitializeRobot();
  waitForStart();
  if(blueSide){
  distForward(47);wait1Msec(200);
  turnRightTo(45);wait1Msec(200);
  distForward(16);wait1Msec(200);
  distBackward(2);wait1Msec(200);
  turnRightTo(135);wait1Msec(200);
  distForward(30);wait1Msec(200);
  turnRSideTo(225);wait1Msec(200);
  goBack(500);goRLBack(750);goBack(1000);
}
else{
  //RED SIDE
  distForward(47);wait1Msec(200);
  turnLeftTo(-45);wait1Msec(200);
  distForward(16);wait1Msec(200);
  distBackward(2);wait1Msec(200);
  turnLeftTo(-135);wait1Msec(200);
  distForward(30);wait1Msec(200);
  turnLSideTo(-225);wait1Msec(200);
  goBack(500);goLRBack(750);goBack(1000);
}
  /*
  wait1Msec(3000);//<---insert sonar waiting routine
  turnRightTo(-180);wait1Msec(200);
  distBackward(20);wait1Msec(200);
  turnRightTo(-90);wait1Msec(200);
  distBackward(10);wait1Msec(200);//<--use sonars to detect stack
  turnRightTo(0);wait1Msec(200);
  distBackward(100);wait1Msec(200);
  */
}
