#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  HTMotor)
#pragma config(Sensor, S2,     kGyroSensor,    sensorI2CHiTechnicGyro)
#pragma config(Motor,  motorB,          catchR,        tmotorNormal, PIDControl, encoder)
#pragma config(Motor,  motorC,          catchL,        tmotorNormal, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     LeftSideMotors, tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     RightSideMotors, tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     conveyor1,     tmotorNormal, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     stacker,       tmotorNormal, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C4_1,     spoolL,        tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     spoolR,        tmotorNormal, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    servoCrateL,          tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    servoCrateR,          tServoStandard)
#pragma config(Servo,  srvo_S1_C3_3,    servoGripL,           tServoStandard)
#pragma config(Servo,  srvo_S1_C3_4,    servoGripR,           tServoStandard)
#pragma config(Servo,  srvo_S1_C3_5,    hookL,                tServoStandard)
#pragma config(Servo,  srvo_S1_C3_6,    hookR,                tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "constants.c"
#include "driveMover.c"
#include "JoystickDriver.c" // there's a joystick attached
#include "MovesAuto.c"

////////////////////////////////////////
void initializeRobot(){
  //servoChangeRate[SERVOGATE]   = 10;
  servoChangeRate[ServoCrateL]   = 20;
  servoChangeRate[ServoCrateR]   = 20;
  servoChangeRate[hookL]   = 20;
  servoChangeRate[hookR]   = 20;
  //servoChangeRate[servoFlip] = 10;
  //servoChangeRate[hopControl] = 20;
  //servo[servoFlip] = SERVOARMUP;
  //servo[SERVOGATE]  =  SERVOGATEOPEN;
  servo[servoCrateL]  =  CRATELUP;
  servo[servoCrateR]  =  CRATERUP;
  servo[servoGripL]  =  GRIPLTHIN;
  servo[servoGripR]  =  GRIPRTHIN;
  servo[hookL]  =  hookfoldL;
  servo[hookR]  =  hookfoldR;
  //servo[hopControl] = HOPCONTROLCLOSED;
  nMotorEncoder[stacker]=0;
  motor[motorB]=-50;
  motor[motorC]=-50;
  wait1Msec(250);
  nMotorEncoder[motorB]=0;
  nMotorEncoder[motorC]=0;
  motor[motorB]=0;
  motor[motorC]=0;
}

task main()
{
  bool gonext; //used to gate input/output
  bool blueSide=false;
  bool getBowlBall=false;
  bool B_haveBBall=false;


  //BEGINNING OF NXT BUTTON INPUT
  gonext=false;
  nNxtButtonTask=0;
  hogCPU();

  //SIDE SELECTION
  while(!gonext){

    ClearTimer(T1);
      nxtDisplayCenteredBigTextLine(1, "SIDE");
      if(blueSide) nxtDisplayCenteredBigTextLine(3, "BLUE");
      else          nxtDisplayCenteredBigTextLine(3, "RED");

    while(time10[T1]<20);
    if(nNxtButtonPressed == 1) blueSide=true;
    if(nNxtButtonPressed == 2) blueSide=false;
    if(nNxtButtonPressed == 3) gonext=true;
  }

  if(blueSide) {
    ClearTimer(T1);
    while(time10[T1]<50);  //wait for 1/2 second to make sure button released
  }
  else {
    ClearTimer(T1);
    while(time10[T1]<50);  //wait for 1/2 second to make sure button released
  }

  //QUERY GET BOWLING BALL
  gonext=false;
  while(!gonext){
    if(blueSide) {
      nxtDisplayCenteredBigTextLine(1, "BLUE");
    }
    else {
      nxtDisplayCenteredBigTextLine(1, "RED");
    }

    if(getBowlBall) nxtDisplayCenteredBigTextLine(3, "GETBALL");
    else            nxtDisplayCenteredBigTextLine(3, "STRAIGHT");

    ClearTimer(T1);
    while(time10[T1]<20);
    if(nNxtButtonPressed == 1) {getBowlBall=true;  }
    if(nNxtButtonPressed == 2) {getBowlBall=false; }
    if(nNxtButtonPressed == 3) gonext=true;
  }

  nNxtButtonTask=-1;
  releaseCPU();

  InitializeRobot();

	waitForStart();
	//motor[motorB]=-1;
  //motor[motorC]=-1;
	//wait1Msec(3000);

  ClearTimer(T1);  //we can use timer T1 to wait etc
                   //we should use time100 timer since that allows enough time for autonomous
                   //time100[T1]=300 is end of autonomous

  //advance to goal and turn
  if(blueSide){
    if(getBowlBall){
      distForward(42);wait1Msec(200);
      turnRightTo(45);wait1Msec(200);
      distForward(16);wait1Msec(200);
      distBackward(6);wait1Msec(200);
      turnRightTo(125);wait1Msec(200);
      //servo[servoGate]  =  SERVOGATEOPEN;
      distForward(12);
      //should now be facing ball
      goForward(1500);

      distForward(60);
      turnLeftTo(45);
      distForward(28);
    }//END of get bowl ball blue
    else { //non-ball side: knock crates
     /* distForward(45);wait1Msec(200);
      //turnRight45();wait1Msec(200);
      angleRight(45);wait1Msec(200);
      distForward(24);wait1Msec(200);
      //could try adding going to parking zone
      */
      distForward(150);
    }

  }
  else { //RED SIDE
    if(getBowlBall){
      distForward(42);wait1Msec(200);
      turnLeftTo(-45);wait1Msec(200);
      distForward(16);wait1Msec(200);
      distBackward(6);wait1Msec(200);
      turnLeftTo(-125);wait1Msec(200);
      //servo[servoGate]  =  SERVOGATEOPEN;
      distForward(12);
      //should now be facing ball
      goForward(1500);

      distForward(60);
      turnRightTo(-45);
      distForward(28);
    }
    else { //non-ball side: knock crates
      /*
      distForward(45);wait1Msec(200);
      //turnLeft45();wait1Msec(200);
      angleLeft(45);wait1Msec(200);
      distForward(24);wait1Msec(200);
      //could try adding going to parking zone
      */
      distForward(150);
    }
  }
  ////////////

}
