#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S2,     kGyroSensor,    sensorI2CHiTechnicGyro)
#pragma config(Sensor, S3,     S_lightsensor,  sensorLightActive)
#pragma config(Sensor, S4,     HTIRS2,              sensorI2CCustom)
#pragma config(Motor,  mtr_S1_C1_1,     M_DriveFL,     tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     M_DriveBR,     tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     M_DriveFR,     tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     M_DriveBL,     tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     M_Lift,        tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C3_2,     M_Unused,      tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C4_1,    SV_TiltLeft,          tServoStandard)
#pragma config(Servo,  srvo_S1_C4_2,    SV_TiltRight,         tServoStandard)
#pragma config(Servo,  srvo_S1_C4_3,    SV_Swivel,            tServoStandard)
#pragma config(Servo,  srvo_S1_C4_4,    SV_LightSensor,       tServoStandard)
#pragma config(Servo,  srvo_S1_C4_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.
#include "InputParameters.c"
#include "CHSGyroDriver.c"
#include "constants.c"

int expectedGyro=0;


#include "Pautosub.c"

 //used to integrate and track rotations

void reInitializeGyro(){
	fGyroAngle=0;
	expectedGyro=0;
}


int initialDelay;
int dir1,dir2,dir3;
float rng1,rng2,rng3;

void getPlan(){
	hogCPU();
	initialDelay=getIntTarget("intl del msec",0,31000);
	dir1=getIntTarget("direction 1",0,7); dir1=dir1%8;
	rng1=getFloatTarget("range 1",0,120);
	dir2=getIntTarget("direction 2",0,7); dir2=dir2%8;
	rng2=getFloatTarget("range 2",0,120);
	dir3=getIntTarget("direction 3",0,7); dir3=dir3%8;
	rng3=getFloatTarget("range 3",0,120);
	releaseCPU();
}

int displayPlan(){
	string line;
	hogCPU();
	eraseDisplay();
	while(nNxtButtonPressed == 3){};
	while(nNxtButtonPressed == -1 ){
		nxtDisplayCenteredTextLine(1,"Delay %d",initialDelay);
		nxtDisplayCenteredTextLine(2,"D %d R %6.1f",dir1,rng1);
		nxtDisplayCenteredTextLine(3,"D %d R %6.1f",dir2,rng2);
		nxtDisplayCenteredTextLine(4,"D %d R %6.1f",dir3,rng3);
		nxtDisplayCenteredTextLine(5,"orange accept");
		nxtDisplayCenteredTextLine(6,"arrow redo");
	}
	eraseDisplay();
	releaseCPU();
	return nNxtButtonPressed;
}

void initializeRobot(){
	//StartTask(GyroDeviceDriver,255);


  servoChangeRate[SV_TiltLeft]        = 10;
  servoChangeRate[SV_TiltRight]       = 10;
  servoChangeRate[SV_Swivel]          = 10;
  servoChangeRate[SV_LightSensor]      = 0;

  nMotorEncoder[M_Lift]    = 0;

  servo[SV_Swivel]=C_SVSWIVELCENTER;
  servo[SV_TiltRight]=C_SVTILTRIGHTUP;
  servo[SV_TiltLeft]=C_SVTILTLEFTUP;
  servo[SV_LightSensor]=C_SVLIGHTSENSORIN;

  wait1Msec(2000);
  servo[SV_TiltRight]=C_SVTILTRIGHTDOWN;
  servo[SV_TiltLeft]=C_SVTILTLEFTDOWN;
  wait1Msec(200);
  servo[SV_TiltRight]=C_SVTILTRIGHTUP;
  servo[SV_TiltLeft]=C_SVTILTLEFTUP;

  reInitializeGyro();//should be initialized anyway


  // the default DSP mode is 1200 Hz.
  //tHTIRS2DSPMode _mode = DSP_1200;
}


task main()
{


	int butt;
	do{
		getPlan();
		butt=displayPlan(); //orange button is accept
	}while(butt!=3);


	initializeRobot();

  waitForStart(); // Wait for the beginning of autonomous phase.

  //PATH EXECUTE
  //Delay
  wait1Msec(initialDelay);
  autoDrive(dir1,rng1); wait1Msec(200);
  autoDrive(dir2,rng2); wait1Msec(200);
  autoDrive(dir3,rng3); wait1Msec(200);
  //go dir2 for rng2
  //go dir3 for rng3
}
